# Generated by Django 5.0.8 on 2024-08-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='title',
        ),
    ]
